version: '3.8'
services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: muzmatch
      MYSQL_USER: banana
      MYSQL_PASSWORD: pancakes
    ports:
      - '4306:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql
  php:
    container_name: php
    build:
      context: ./docker
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/muzmatch
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/muzmatch
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database