hello:
  path: /
  controller: App\Controller\UserController::hello

create:
  path: /user/create
  controller: App\Controller\UserController::create

swipe:
  path: /swipe/{loggedInUser}/{swipedUser}/{attracted}
  controller: App\Controller\UserController::swipe

profiles:
  path: /profiles/{loggedInUserId}
  controller: App\Controller\UserController::profiles